name: Actions Workflof
on: 
  push:
    #branches:
    #  - master
    #  - 'feature/*' 
    #  - 'feature/**'
    #  - '!feature/featC' #to ignore this branch
    #tags:
    #  - v1.*
    paths:
    #  - '**.js'
      - '**/actions.yml'
    #paths-ignore:
     #- 'docs/**'
  #repository_dispatch: 
  #  types: [build]
  #schedule:
  #  - cron: '*/10 * * * *'
  #  - cron: '0/6 * * * *'
  #push:
  #pull_request:
  #  types: [closed, assigned, opened, reopened]

jobs:
  run-github-actions:
    runs-on: windows-latest
    steps:
      #- name: payload
      #  run: echo ${{ github.event.client_payload.env }}
      - name: list files
        run:  |
          pwd
          ls 
          echo "GITHUB_SHA: ${GITHUB_SHA}"
          echo "GITHUB_REPOSITORY: ${GITHUB_REPOSITORY}"
          echo "GITHUB_WORKSPACE: ${GITHUB_WORKSPACE}"
          echo "${{ github.token }}"
      - name: Checkout
        uses: actions/checkout@v1
      - name: list files
        run:  |
          pwd
          ls 
      - name: Simpe Java script action 
        id: Greeting
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: Krešo
      - name: Log Greeting Time
        run: echo "˘${{ steps.Greeting.outputs.time }}"
      - name: Directory path
        run: pwd
        
