name: Matrix
on: 
  push:
    paths:
      - '**/matrix.yml'

jobs: 
  node-version:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        node_version: [11,12,13]
        include:
          - os: ubuntu-latest
            node-version: 11
            is_ubuntu_11: true
        exclude:
          - os: ubuntu-latest
            node-version: 12
          - os: windows-latest
            node-version: 13
      max-parallel: 5
      fail-fast: false
    runs-on: ${{ matrix.os }}
    env:
      IS_UBUNTU_11: ${{ matrix.is_ubuntu_11 }}
    steps:
      - name: Log node version
        run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: Log node version
        run: |
          node -v
          echo $IS_UBUNTU_11


