name: Matrix
on: 
  push:
    paths:
      - '**/matrix.yml'

jobs: 
  node-version:
    strategy:
      matrix:
        
        node_version: [11,12,13]
      max-parallel: 2
      fail-fast: true
    runs-on: windows-latest
    steps:
      - name: Log node version
        run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node_version }}
      - name: Log node version
        run: node -v

