name: Matrix
on: 
  push:
    paths:
      - '**/matrix.yml'

jobs: 
  node-version:
    runs-on: windows-latest
    steps:
      - name: Log node version
        run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Log node version
        run: node -v