name: Shell Commands

on: [push, pull_request]

jobs: 
  run-shell-command:
    runs-on: windows-latest
    steps:
      - name: echo a string
        run: eccho "Hello world"
      - name: multiline script
        run: |
          node -v
          npm -v
